version: "3"
networks:
  app-tier:
    driver: bridge
services:
  
  nats:
    image: 'bitnami/nats:latest'
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - app-tier
  worker:
    build: ./worker
    networks:
      - app-tier
    depends_on:
      - nats
    environment:
      - NATSIPADDR=nats:4222
  api:
    build: ./frontend
    ports:
      - '3000:3000'
    networks:
      - app-tier
    depends_on:
      - nats
    environment:
      - SESSION=Natssesion
      - NATSIPADDR=nats:4222
      - PORT=3000
